---
- name: Merge basic configuration
  hosts: ALL
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
  - name: Push basic configuration with NAPALM
    napalm_install_config:
        optional_args: {'global_delay_factor': 1}
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password: "{{ ansible_ssh_pass }}"
        config_file: "{{ config_dir }}/{{ inventory_hostname }}/1_basic-config.conf"
        commit_changes: True
        replace_config: "{{ replace_config }}"
        diff_file: "{{ config_dir }}/{{ inventory_hostname }}/1_basic-config.diff"