---

- name: generate stp-config from templates
  when: inventory_hostname in groups['switches']
  template: src=../templates/{{ansible_network_os}}.j2 dest={{config_dir}}/{{inventory_hostname}}/2_stp-config.conf