---
- name: Push all full FINAL configuration
  hosts: ALL
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:

  # Push the single FINAL conf:
  - name: Push 'FINAL.conf' configuration with NAPALM (DO execute 'FINAL.conf' config)
    when: inventory_hostname != 'HQ-FW1'
    napalm_install_config:
        optional_args: {'global_delay_factor': 1}
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password: "{{ ansible_ssh_pass }}"
        config_file: "{{ config_dir }}/{{ inventory_hostname }}/FINAL.conf"
        commit_changes: True
        replace_config: "{{ replace_config }}"
        diff_file: "{{ config_dir }}/{{ inventory_hostname }}/FINAL.diff"