---

- name: generate GLBP config from templates
  when: inventory_hostname in groups['GLBP']
  template: src=../templates/{{ansible_network_os}}.j2 dest={{config_dir}}/{{inventory_hostname}}/6_glbp-config.conf